name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: build and check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - run: bundle exec jekyll build
      - run: bundle exec htmlproofer ./_site --disable-external --ignore-empty-alt
